ROOT_PATH = '/home/algorithm/musicProject/'
DATA_PATH = ROOT_PATH + 'data'
MIDI_FILE_PATH = ROOT_PATH + 'data/midi'
NP_FILE_PATH = ROOT_PATH + 'data/np'
MODEL_PATH = ROOT_PATH + 'trained'
MUSIC_PATH = ROOT_PATH + 'music'


PHRASE_SIZE = 4
BAR_SIZE = 96
PITCH_SIZE = 96 # 128
BEAT_RESOLUTION = 24
TIME_SIGNATURES = ['4/4']
MINIMUM_NOTE = 8


GAN_EPOCH = 10
CLASSIFIER_EPOCH = 500
BATCH_SIZE = 128
